spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/hospital
#    url: jdbc:postgresql://localhost:5432/hospital
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/1.0.0/db.changelog-1.0.0.yaml
  kafka:
    bootstrap-servers: kafka:9092
#    bootstrap-servers: localhost:9092

application:
  api-service:
    url: api-service:8080
#    url: localhost:8080

kafka:
  registration-topic: "registration_topic"
  group-id: "groupId"

server:
  port: 8081
